roiim/payment/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<product_pk>[0-9]+)/$",
        views.payment_start,
        name="start",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/details/$",
        views.payment_details,
        name="details",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/details/(?P<payment_pk>[0-9]+)/success/$",
        views.payment_success,
        name="success",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/details/(?P<payment_pk>[0-9]+)/complete/$",
        views.payment_final,
        name="final",
    ),
      url(
        r"^order/details/$",
        views.order_details,
        name="order-details",
    ),
]

roiim/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<product_pk>[0-9]+)/$",
        views.product_details,
        name="details",
    ),
    url(
        r"^$",
        views.product_list,
        name="list",
    )
]

roiim/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

from .product.urls import urlpatterns as product_urls
from .user.urls import urlpatterns as user_urls
from .payment.urls import urlpatterns as payment_urls
from .product.views import base, login_redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    path('', base),
    url(r"^user/", include((user_urls, "user"), namespace="user")),
    url(r"^payment/", include((payment_urls, "payment"), namespace="payment")),
    url(r"^accounts/profile/", login_redirect),
]

roiim/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^signup/(?P<product_pk>[0-9]+)/$",
        views.signup,
        name="signup",
    ),
    url(
        r"^logout/$",
        views.logout,
        name="logout",
    ),
    url(
        r"^login/$",
        views.login,
        name="login",
    ),
]

roiim/product/models.py
from django.db import models
from django.conf import settings


class AuditModel(models.Model):
    """
    Abstract Audit model class to be used in all the models
    """
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Product(AuditModel):
    """
    Model to store Product Details
    """
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,)
    is_visible = models.BooleanField(default=True)

    class Meta:
        app_label = "product"
        ordering = ("name",)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

roiim/product/views.py
from django.shortcuts import render, redirect, reverse
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required

from .models import Product


def base(request):
    return redirect(reverse("product:list"))

def login_redirect(request):
    return redirect(reverse("product:list"))    

def product_list(request):
    products = Product.get_all_products()
    ctx = {"products": products}
    return TemplateResponse(request, 'product/product_list.html', ctx)

@login_required
def product_details(request, product_pk):
    if not request.user.is_authenticated:
        return redirect(reverse('product:list'))
    product = Product.objects.get(pk=product_pk)
    user = request.user
    ctx={
            "product": product,
            "user": user,
        }
    return TemplateResponse(request, 'product/product_details.html', ctx)

templates/product/list_products.html
{% for product in products %}
<div class="col-md-4 col-sm-12 mob-text-center">
  <!-- <a href="{{ product.get_absolute_url }}" class="d-block brand-card mb-4 link--clean"> -->
    <a href="products/1" class="d-block brand-card mb-4 link--clean">
        <img class="img-responsive lazyload lazypreload mw-100"
              data-src="https://images.boardriders.com/globalGrey/quiksilver-products/all/default/large/eqyft04097_towelhood,w_bsm0_frt1.jpg"
              data-srcset="https://images.boardriders.com/globalGrey/quiksilver-products/all/default/large/eqyft04097_towelhood,w_bsm0_frt1.jpg"
              alt=""
              src="https://images.boardriders.com/globalGrey/quiksilver-products/all/default/large/eqyft04097_towelhood,w_bsm0_frt1.jpg">
    <div class="row">
      <div class="col-sm-12">
        <!-- <h2 class="section-header-rg header-dark font-semi-bold mb-2 mt-0">{{ product.translated }}</h2> -->
      </div>
    </div>
    <div class="row">

    </div>
  </a>
</div>

{% endfor %}

templates/product/product_details.html
{% extends "base.html" %}
{% load static %}

{% block navbar-item %}
<a class="nav-link" href="{% url 'payment:order-details' %}">Your Orders</a>
{% endblock %}
{% block logout %}
<a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
{% endblock %}

{% block page_content %}
<h1>{{ product.name }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="https://picsum.photos/400" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the product:</h5>
        <p>{{ product.description }}</p>
        <br>
        <h5>Price:</h5>
        <p>Rs. {{ product.price }}</p>
        <a href="{% url 'payment:start' product_pk=product.id %}" class="btn btn-primary">
            Pay and Order
          </a>
    </div>
</div>
{% endblock %}

templates/product/product_list.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-lg-12 my-3">
            <div class="pull-right">
            </div>
            <div>
                {% if messages %}
                    {% for message in messages %}
                      <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                      </div>
                    {% endfor %}
                  {% endif %}
            </div> 
        </div>
       
    </div>
   

       
        <div id="products" class="row view-group">
            {% for product in products %}
        <div class="item col-xs-4 col-lg-4">
            <div class="thumbnail card">
                <div class="img-event">
                    <img class="group list-group-image img-fluid" src="https://picsum.photos/400/250" alt="" />
                </div>
                <div class="caption card-body">
                    <h4 class="group card-title inner list-group-item-heading">
                        {{ product.name }}</h4>
                    <p class="group inner list-group-item-text">
                       {{ product.description }}</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                Rs. {{ product.price }}</p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" href="{% url 'user:signup' product_pk=product.id %}">Buy Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>