roiim/payment/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<product_pk>[0-9]+)/$",
        views.payment_start,
        name="start",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/details/$",
        views.payment_details,
        name="details",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/details/(?P<payment_pk>[0-9]+)/success/$",
        views.payment_success,
        name="success",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/details/(?P<payment_pk>[0-9]+)/complete/$",
        views.payment_final,
        name="final",
    ),
      url(
        r"^order/details/$",
        views.order_details,
        name="order-details",
    ),
]

roiim/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

from .product.urls import urlpatterns as product_urls
from .user.urls import urlpatterns as user_urls
from .payment.urls import urlpatterns as payment_urls
from .product.views import base, login_redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    path('', base),
    url(r"^user/", include((user_urls, "user"), namespace="user")),
    url(r"^payment/", include((payment_urls, "payment"), namespace="payment")),
    url(r"^accounts/profile/", login_redirect),
]

roiim/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^signup/(?P<product_pk>[0-9]+)/$",
        views.signup,
        name="signup",
    ),
    url(
        r"^logout/$",
        views.logout,
        name="logout",
    ),
    url(
        r"^login/$",
        views.login,
        name="login",
    ),
]

roiim/payment/models.py
import requests
import json
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

from ..product.models import Product, AuditModel


class CardDetails(AuditModel):
    card_number = models.CharField(max_length=16, unique=True)
    expiry_month = models.CharField(max_length=2)
    expiry_year = models.CharField(max_length=4)
    holder_name = models.CharField(max_length=128)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='card')

    @staticmethod
    def save_card(card_number, expiry_month, expiry_year, holder_name, user):
        if not CardDetails.objects.filter(card_number=card_number).exists():
            CardDetails.objects.create(card_number=card_number, expiry_month=expiry_month, expiry_year=expiry_year,
                holder_name=holder_name, user=user)

class Payment(AuditModel):
    STATUS_SUCCESS = 1
    STATUS_ERROR = 2
    STATUS_IN_PROCESS = 0
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='payment')
    card = models.ForeignKey(CardDetails, on_delete=models.CASCADE)
    status = models.IntegerField(blank=True)
    token = models.CharField(max_length=128, blank=True)

    @staticmethod
    def create_payment(product, cardnumber, status):
        card = CardDetails.objects.get(card_number=cardnumber)
        payment = Payment.objects.create(product=product, card=card, status=status)
        payment.save()
        return payment


    @staticmethod
    def create_payment_handle(card_number, expiry_month, expiry_year,
        holder_name, cv_code, amount, nickname,
        street, city, postal_code, country, product):
        payment = Payment.create_payment(product=product, cardnumber=card_number, status=Payment.STATUS_IN_PROCESS)
        url = "https://api.test.paysafe.com/paymenthub/v1/paymenthandles"
        headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Basic {}'.format(settings.BASE64_API_KEY),
        'Simulator': '"EXTERNAL"'
        }
        payload = {
            'merchantRefNum': payment.id,
            'transactionType': "PAYMENT",
            'card': {
                'cardNum': card_number,
                'cardExpiry':{
                    'month': expiry_month,
                    'year': expiry_year
                    },
                'cvv': cv_code,
                "holderName": holder_name,
                },
            "paymentType": "CARD",
            "amount": int(amount),
            "currencyCode": "USD",
            "billingDetails": {
                "nickName": nickname,
                "street": street,
                "city": city,
                "zip": postal_code,
                "country": country
            },
            "returnLinks": [{
            "rel": "on_completed",
            "href": "http://shivam-app.com/payment/{}/details/success".format(product.id),
            # 'href': reverse('payment:success' kwargs={'payment_pk':payment.id, 'paymentHandleToken'}),
            "method": "GET"
            },
            {
            "rel": "on_failed",
            "href": "http://shivam-app.com/products/",
            "method": "GET"
            },
            {
            "rel": "default",
            "href": "http://shivam-app.com/products/",
            "method": "GET"
            }
            ]            
        }
        payload = json.dumps(payload)
        response = requests.request("POST", url, headers=headers, data = payload)
        r = response.json()
        if response.status_code == 201:
            payment.token = r['paymentHandleToken']
            payment.save(update_fields=['token'])
        print(response.status_code)
        
        print(response.text.encode('utf8'))
        return response
    
    @staticmethod
    def pay_for_product(product, payment):
        url = "https://api.test.paysafe.com/paymenthub/v1/payments"
        headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Basic {}'.format(settings.BASE64_API_KEY),
        'Simulator': '"EXTERNAL"'
        }
        payload = {
        "merchantRefNum": payment.id,
        "amount": int(product.price),
        "currencyCode": "USD",
        "dupCheck": "true",
        "settleWithAuth": "false",
        "paymentHandleToken": payment.token,
        "description": product.description
        } 
        payload = json.dumps(payload)
        response = requests.request("POST", url, headers=headers, data = payload)
        r = response.json()
        if response.status_code == 201 and r['status'] == 'COMPLETED':
            payment.status = Payment.STATUS_SUCCESS
            payment.save(update_fields=['status'])
        else:
            payment.status = Payment.STATUS_ERROR
            payment.save(update_fields=['status'])
        print(response.text)
        return response

roiim/payment/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse
from django.contrib import messages

from ..product.models import Product
from .models import CardDetails, Payment

@login_required
def payment_start(request, product_pk):
    if not request.user.is_authenticated:
        return redirect(reverse("product:list"))
    product = Product.objects.get(pk=product_pk)
    user = request.user
    ctx = {
        "product": product,
        "user":user,
    }
    return TemplateResponse(request, "payment/start.html", ctx)


@login_required
def payment_details(request, product_pk):
    if not request.user.is_authenticated:
        return redirect(reverse("product:list"))
    product = Product.objects.get(pk=product_pk)
    user = request.user
    card_number = request.POST.get('cardnumber')
    expiry_month = request.POST.get('expirymonth')
    expiry_year = request.POST.get('expiryyear')
    holder_name = request.POST.get('holdername')
    cv_code = request.POST.get('cvcode')
    remember = request.POST.get('remember')
    amount = product.price
    # if remember:
    CardDetails.save_card(card_number, expiry_month, expiry_year, holder_name, user)
    nickname = request.POST.get('nickname')
    street = request.POST.get('street')
    city = request.POST.get('city')
    postal_code = request.POST.get('zip')
    country = request.POST.get('country')
    response = Payment.create_payment_handle(
        card_number, expiry_month, expiry_year,
        holder_name, cv_code, amount, nickname,
        street, city, postal_code, country, product
    )
    r = response.json()
    if response.status_code == 201:
        return redirect(reverse('payment:success', kwargs={'product_pk':product_pk, 'payment_pk':r['merchantRefNum']}))
    
    messages.error(request, ("Error: something went wrong"))
    ctx = {
        "product": product,
        "user":user,
    }
    return TemplateResponse(request, "payment/start.html", ctx)

@login_required
def payment_success(request, product_pk, payment_pk):
    product = Product.objects.get(pk=product_pk)
    payment = Payment.objects.get(pk=payment_pk)
    user = request.user
    # if not payment.status == Payment.STATUS_SUCCESS:
    #     Payment.pay_for_product(product, payment)

    ctx = {
        "product": product,
        "user":user,
        "payment":payment,
    }
    return TemplateResponse(request, "payment/detail.html", ctx)

@login_required
def payment_final(request, product_pk, payment_pk):
    product = Product.objects.get(pk=product_pk)
    payment = Payment.objects.get(pk=payment_pk)
    user = request.user
    if not payment.status == Payment.STATUS_SUCCESS:
        response = Payment.pay_for_product(product, payment)
    else:
        messages.success(request, ("You already did the payment!"))
        return redirect(reverse("payment:order-details"))
    if response.status_code == 201:
        return redirect(reverse("payment:order-details"))
    messages.error(request, ("Error: something went wrong"))
    ctx = {
        "product": product,
        "user":user,
        "payment":payment,
    }
    return TemplateResponse(request, "payment/detail.html", ctx)

@login_required
def order_details(request):
    user = request.user
    # products = Product.objects.filter(payment__card__user=user)
    cards = CardDetails.objects.filter(user=user)
    payments = Payment.objects.filter(card__in=cards, status=Payment.STATUS_SUCCESS)
    products = Product.objects.filter(payment__in=payments)

    ctx = {
        "products": products,
        "user": user,
    }
    return TemplateResponse(request, "payment/orders.html", ctx)

templates/payment/detail.html
{% extends "base.html" %}

{% block navbar-item %}
<a class="nav-link" href="{% url 'payment:order-details' %}">Your Orders</a>
{% endblock %}
{% block logout %}
<a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
{% endblock %}

{% block page_content %}
<p> Payment of INR {{ product.price }} is being processed for product: {{ product.name }}
    with transaction ID: {{ payment.token }}
    <br>
    <a href="{% url 'payment:final' payment_pk=payment.id product_pk=product.id %}" class="btn btn-success">Click Here</a> to Confirm.
</p>
{% endblock %}

templates/payment/orders.html
{% extends "base.html" %}

{% block navbar-item %}
<a class="nav-link" href="{% url 'payment:order-details' %}">Your Orders</a>
{% endblock %}
{% block logout %}
<a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
{% endblock %}
{% block page_content %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-lg-12 my-3">
            <div class="pull-right">
            </div>
        </div>
    </div> 
    <h2>These are the product ordered and paid by {{ user.username }}</h2>
    <div id="products" class="row view-group">
        {% for product in products %}
        <div class="item col-xs-4 col-lg-4">
            <div class="thumbnail card">
                <div class="img-event">
                    <img class="group list-group-image img-fluid" src="https://picsum.photos/400/250" alt="" />
                </div>
                <div class="caption card-body">
                    <h4 class="group card-title inner list-group-item-heading">
                        {{ product.name }}</h4>
                    <p class="group inner list-group-item-text">
                       {{ product.description }}</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                Rs. {{ product.price }}</p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <!-- <a class="btn btn-success" href="{% url 'user:signup' product_pk=product.id %}">Buy Now</a> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <br>
    <a href="{% url 'user:logout' %}" class="btn-success">Logout</a>
</div>
{% endblock %}

templates/payment/start.html
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->


<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-4">
            {% if messages %}
            {% for message in messages %}
              <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Payment Details
                    </h3>
                    <form name='form' method="POST" action="{% url 'payment:details' product_pk=product.id %}">
                    <div class="checkbox pull-right">
                        <label>
                            <input type="checkbox" name='remember' value='1'/>
                            Remember
                        </label>
                    </div>
                </div>
                <div class="panel-body">
                    <!-- <form name='form' method="POST" action="{% url 'payment:details' product_pk=product.id %}"> -->
                        {% csrf_token %}
                    <div class="form-group">
                        <label for="cardNumber">
                            CARD NUMBER</label>
                        <div class="input-group">
                            <input type="text" name="cardnumber" class="form-control" id="cardNumber" placeholder="Valid Card Number"
                                required autofocus />
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-7 col-md-7">
                            <div class="form-group">
                                <label for="expityMonth">
                                    EXPIRY DATE</label>
                                <div class="col-xs-6 col-lg-6 pl-ziro">
                                    <input type="text" class="form-control" name="expirymonth" id="expiryMonth" placeholder="MM" required />
                                </div>
                                <div class="col-xs-6 col-lg-6 pl-ziro">
                                    <input type="text" class="form-control" name="expiryyear" id="expiryYear" placeholder="YYYY" required /></div>
                            </div>
                            <br>
                            <br> 
                            <div class="form-group">
                                <label for="holderName">
                                    Holder's Name</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="holdername" id="holderName" placeholder="Your Name"
                                        required autofocus />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="nickName">
                                    Nick Name</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="nickname" id="nickName" placeholder="Your Nick Name"
                                        required autofocus />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="street">
                                    Street</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="street" id="street" placeholder="Street"
                                        required autofocus />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="city">
                                    City</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="city" id="city" placeholder="City"
                                        required autofocus />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="zip">
                                    Zip</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="zip" id="zip" placeholder="Zip"
                                        required autofocus />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="country">
                                    Country Code</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="country" id="city" placeholder="Country Code example: IN"
                                        required autofocus />
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-5 col-md-5 pull-right">
                            <div class="form-group">
                                <label for="cvCode">
                                    CV CODE</label>
                                <input type="password" class="form-control" name="cvcode" id="cvCode" placeholder="CV" required />
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#"><span class="badge pull-right"><span class="fa fa-inr"></span> {{ product.price }} </span> Final Payment</a>
                </li>
            </ul>
            <br/>
            <button type="submit" class="btn btn-success btn-lg btn-block" role="button" type="submit">Pay</button>
        </form>
        </div>
    </div>
</div>

<style>
    .container{
        width: 1000px;
        height: 500px;
        position: absolute;
        left: 75%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
</style>