roiim/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

from .product.urls import urlpatterns as product_urls
from .user.urls import urlpatterns as user_urls
from .payment.urls import urlpatterns as payment_urls
from .product.views import base, login_redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    path('', base),
    url(r"^user/", include((user_urls, "user"), namespace="user")),
    url(r"^payment/", include((payment_urls, "payment"), namespace="payment")),
    url(r"^accounts/profile/", login_redirect),
]

roiim/user/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^signup/(?P<product_pk>[0-9]+)/$",
        views.signup,
        name="signup",
    ),
    url(
        r"^logout/$",
        views.logout,
        name="logout",
    ),
    url(
        r"^login/$",
        views.login,
        name="login",
    ),
]

roiim/user/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
# Create your models here.
# User = get_user_model()

# class User(AbstractUser):
#     pass

roiim/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import forms as django_forms

User = get_user_model()


class SignupForm(forms.ModelForm):
    required_css_class = 'required'
    email = forms.EmailField(
        label="Email Address",
        error_messages={
            "unique": (
                "Registration error")
        }
    )

    class Meta:
        model = User
        fields = ("username", "email", "password", )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def save(self, request=None, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data["password"]
        user.set_password(password)
        if commit:
            user.save()
        return user

class LoginForm(django_forms.AuthenticationForm):

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request=request, *args, **kwargs)

roiim/user/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib import auth, messages
from django.contrib.auth import views as django_views
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings

from ..product.models import Product
from .forms import SignupForm, LoginForm

# Create your views here.

def signup(request, product_pk):
    print(request.user)
    if request.user.is_authenticated:
        return redirect(reverse('product:details', kwargs={'product_pk':product_pk}))
    product = Product.objects.get(pk=product_pk)
    form = SignupForm(request.POST or None)
    if form.is_valid():
        form.save()
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        username = form.cleaned_data.get("username")
        user = auth.authenticate(request=request, username=username, password=password)
        try:
            if user:
                auth.login(request, user)
        except Exception as e:
            print(e)
        messages.success(request, ("User has been created"))
        # redirect_url = request.POST.get("next", "http://localhost:8000/products/1")
        redirect_url = reverse('product:details', kwargs={'product_pk':product_pk})
        return redirect(redirect_url)
    ctx = {
            "form": form,
            "product":product, }
    return TemplateResponse(request, "user/signup.html", ctx)

@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, ("You have been successfully logged out."))
    return redirect(reverse('product:list'))

def login(request):
    kwargs = {"template_name": "user/login.html", "authentication_form": LoginForm}
    return django_views.LoginView.as_view(**kwargs)(request, **kwargs)

templates/user/login.html
{% extends "base.html" %}
{% load bootstrap_form from bootstrap4 %}
{% block page_content %}
<form method="post" action="{% url 'user:login' %}" novalidate>
    {% csrf_token %}
    <fieldset>
      {% bootstrap_form form %}
      {% if REDIRECT_FIELD_VALUE %}
        <input type="hidden" name="{{ REDIRECT_FIELD_NAME }}" value="{{ REDIRECT_FIELD_VALUE }}"/>
      {% endif %}
    </fieldset>
    <div class="row login__btn-group">
      <div class="col-sm-12">
        <button class="btn btn-primary narrow">
          Log in
        </button>
            <hr>
            <div class="row">
            </div>
      </div>
    </div>
  </form>
  
{% endblock %}

templates/user/signup.html
{% extends "base.html" %}
{% load bootstrap_form from bootstrap4 %}
{% block page_content %}
<div class="col-lg-10 col-sm-12 m-auto">
    <div class="row login">
       <div class="col-md-6 login__register">
        <div class="login__register-link">
          <h3>Already have an account?</h3>
          
          <p><a rel="nofollow" href="{% url 'user:login' %}" class="btn secondary narrow">
            Log in
          </a></p>
        </div>
      </div> 
       <div class="col-md-8 login__form">
        <form method="post" action="{% url 'user:signup' product_pk=product.id %}">
          <fieldset>
            <h3>Create an Account</h3>
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if REDIRECT_FIELD_VALUE %}
              <input type="hidden" name="{{ REDIRECT_FIELD_NAME }}" value="{{ REDIRECT_FIELD_VALUE }}"/>
            {% endif %}
          </fieldset>
          <div class="button">
          <button type="submit" class="btn btn-primary narrow">
            Create an account
          </button>
          </div>
        </form>
      </div> 
    </div>
  </div>
  <style>
    .required label:after{
      color: red;
      content: " *";
    }
    .login__form {
      background-color: white;
    }
    .button  {
      margin-left: 455px;
    }
  </style>
{% endblock %}